[package]
name = "peer_2_peer"
version = "0.1.0"
authors = ["hugozoells"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = "0.22.0"
futures = "0.3.5"
async-std = "1.6.2"
env_logger = "0.7.1"
